### ISSUE TITLE
specify the notion of regions

### ISSUE THREAD

**Issue by derhuerst** [public-transport/friendly-public-transport-format#7]
When @juliuste migrated `meinfernbus` to FPTF, we noticed that **there is the concept of regions/cities/hubs**.

Berlin for example has several long-distance train & bus stations, all distinct but well-connected through local public transport. I makes sense to keep them as stations, because they may still have individual stops, but **clustering them would enable more advanced routing information**.

Now questions arise:

- what is the relationship between regions/cities/hubs? `1:n` or `m:n`?
- what name is the best? often these clusters are cities, but not always. sometimes they may be more fine-grained (airport broader area) or less (a Bundesland). "cluster" and "hub" seem very generic.
- where to specify them? should a region/city/hub have a `stations` field or the opposite? or both?

**Comment by derhuerst** [comment]
@juliuste argued that there's actual value in clusters being able to overlap each other, which indicates a `m:n` relationship with `station`s.

**Comment by juliuste** [comment]
As @derhuerst already mentioned, I'd strongly advocate a `m:n` relationship in order to support - or at least to not disable by default - the possibility of assigning multiple `cluster`s to one `station`. For instance: This could be useful when clustering `station`s into both geographical regions and cities. The station `Nice-Ville`  could then be included in the clusters named `Cote d'Azur` **and** `Nice` which - at least to me - really makes sense.

**Comment by juliuste** [comment]
Regarding the naming issue, I'd personally choose between `cluster` and `region`. `cluster` is the more general term while `region` would probably be more easily understandable for people who didn't read the specification when using one of our modules - at least I'd know what do do with a `regions` method while I might not be so sure what a method called `cluster` does. This isn't the strongest or most important argument, still not completely irrelevant though.

Anyway, I wouldn't call the new type `hub`, since this sounds more like an important interchange station than an actual cluster. I'd even call big stations like `Frankfurt Hbf` or - even bigger - `Frankfurt Flughafen` a hub on their own since they serve as an interchange point for quite a decent amount of connections.

**Comment by juliuste** [comment]
On where to specify the relations: As @derhuerst already mentioned in a private discussion, there is no way to reverse engineer the station-cluster-relation starting at a cluster in a lot of cases. Therefore, I'd propose to at least include a `regions` key in `station` object. For practical reasons though, I'd also like to have an additional optional `stations` key in `region` objects to enhance the workflow nice in some situations.

**Comment by juliuste** [comment]
Bump 🔨

**Comment by derhuerst** [comment]
> Therefore, I'd propose to at least include a `regions` key in `station` object. For practical reasons though, I'd also like to have an additional optional `stations` key in `region` objects to enhance the workflow in some situations.

Sounds reasonable to me. However, we should clearly stress what's the preferred direction if only one direction can be specified.

**Comment by derhuerst** [comment]
This might be interesting:

https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping#Voting
https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Metro_Mapping
